services:
  frontend:
    environment:
      - ENVIRONMENT=Production
    container_name: frontend
    image: ${DOCKER_REGISTRY-}psi_frontend
    build:
      context: ./PSI_Frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  event-service:
    container_name: event-service
    image: ${DOCKER_REGISTRY-}event-service
    build:
      context: ./PSI_EventService
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.middleware.conf:/etc/nginx/nginx.conf
    depends_on:
      - event-service
    networks:
      - app-network

  # Postgres inside docker for testing
  postgres-events:
    image: postgres:16
    container_name: postgres-events
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_password
      POSTGRES_DB: events
    volumes:
      - events-pgdata:/var/lib/postgresql/data 
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  events-pgdata: {}
