services:
  frontend:
    ports:
      - 4200:4200
    environment:
      ENVIRONMENT: Dev
      NODE_ENV: development
    build:
      context: ./PSI_Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "/usr/src/app/node_modules"
      - "./PSI_Frontend/:/usr/src/app"

  event-service:
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile.dev
      args:
        SPRING_PROFILES_ACTIVE: dev-docker

  postgres-events:
    ports:
      - "5432:5432"
